export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS"
export const NEW_PLAYLIST    = "NEW_PLAYLIST"
export const FETCH_USER      = "FETCH_USER"

export const PLAYER_IS_PLAYING    = "PLAYER_IS_PLAYING"
export const PLAYER_SHUFFLE       = "PLAYER_SHUFFLE"
export const PLAYER_REPEAT        = "PLAYER_REPEAT"
export const PLAYER_CURRENT_TRACK = "PLAYER_CURRENT_TRACK"