export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS"

export const LOADING    = "LOADING"
export const FETCH_USER = "FETCH_USER"

export const PLAYER_IS_PLAYING     = "PLAYER_IS_PLAYING"
export const PLAYER_SHUFFLE        = "PLAYER_SHUFFLE"
export const PLAYER_REPEAT         = "PLAYER_REPEAT"
export const PLAYER_CURRENT_TRACK  = "PLAYER_CURRENT_TRACK"
export const PLAYER_TRACKLIST      = "PLAYER_TRACKLIST"
export const PLAYER_TRACKLIST_INFO = "PLAYER_TRACKLIST_INFO"

export const FETCH_FAVORITE_TRACKS  = "FETCH_FAVORITE_TRACKS"
export const SET_FAVORITE_TRACKS    = "SET_FAVORITE_TRACKS"